name: ci

on: push


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: check system
      run: |
        lscpu
        free -h
        df -h 
        cat /etc/os-release

    - name: setup
      run: |
        cat /etc/os-release
        bash scripts/setup/start_redis.sh
        bash scripts/setup/install_python_pkgs.sh

    - name: run python
      run: |
        bash scripts/run_python_sub.sh &
        sleep 3
        bash scripts/run_python_pub.sh

    - name: run python async
      run: |
        python src/python/async_case.py